# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa41d253ab508889d22e9ef81bb35142654e69e4f9a25e035de86e23d4c7f152732bc689da7ba749f6cfbf4b2d883e4b9d2e62f3eefec841f0f16be26655ad88

test:
  secret_key_base: e44e41862b88f85acdc768d7247be8d722e3ad46cbeb0bd7d2ed11b3df49c578c6908381d4b38d1780c24f7408e97830b9d6b304cb8b319078a35d0ecafcc51c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
